#! /bin/bash

function error() {
    tput setaf 1
    echo "$1"
    tput sgr0
}

if ! dotnet test > /dev/null 2>&1; then
    error "Tests failed"
    exit 1
fi
echo "Tests passed"

echo "Formatting code..."
mapfile -t files < <(git diff --cached --name-only -- '*.cs')

if (( ${#files[@]} > 0 )); then
    if ! dotnet format --include "${files[@]}" > /dev/null 2>&1; then
        error "Formatting failed"
        exit 1
    fi
    
    git add "${files[@]}"
fi

echo "Code formatted"