#! /bin/bash

function error() {
    tput setaf 1
    echo "$1"
    tput sgr0
    exit 1
}

REPO_ROOT=$(git rev-parse --show-toplevel)

echo "Testing added code..."
tempdir=$(mktemp -d)
trap 'rm -rf "$tempdir"' EXIT

git checkout-index -af --prefix="${tempdir}/"

cd "$tempdir" || error "Failed to setup test environment. Try again later"
if ! dotnet test > /dev/null 2>&1; then error "Tests failed"; fi
echo "Tests passed"


cd "$REPO_ROOT"
echo "Formatting code..."
mapfile -t files < <(git diff --cached --name-only -- '*.cs')

if (( ${#files[@]} > 0 )); then
    dotnet format --include "${files[@]}" > /dev/null 2>&1 || error "Formatting failed"
    git add "${files[@]}"
fi

echo "Code formatted"
