<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>e519a3b0-e53a-42fa-94bd-f2c6b29d739b</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KluskaStore.Application\KluskaStore.Application.csproj" />
      <ProjectReference Include="..\KluskaStore.Domain\KluskaStore.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.*" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.*" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.*" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.*" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.*" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.*" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0" />
    </ItemGroup>

</Project>
